[package]
name = "libsignal-service-actix"
version = "0.1.0"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-service = { path = "../libsignal-service" }
libsignal-protocol = { path = "../../libsignal-protocol-rs/libsignal-protocol" }

awc = { version = "2.0.0-alpha.2", features=["rustls"] }
actix = "0.10.0-alpha.3"
actix-rt = "1.1"
serde_json = "1.0"
futures = "0.3"
bytes = "0.5"
rustls = "0.17"
url = "2.1"
serde = "1.0"
log = "0.4.8"

failure = "0.1.5"
thiserror = "1.0"
async-trait = "0.1.30"

[dev-dependencies]
env_logger = "0.7"
structopt = "0.3"
base64 = "0.12"
qrcode = "0.12"
opener = "0.4"
image = { version = "0.23", default-features = false, features = ["png"] }
