on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  rustfmt:
    name: Verify code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
